// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjvV4UKEGmPaRtgauS-TNOE3W5QQmKMo',
    appId: '1:885247792471:web:45cf33ace8590605d71a12',
    messagingSenderId: '885247792471',
    projectId: 'fir-dfe97',
    authDomain: 'fir-dfe97.firebaseapp.com',
    storageBucket: 'fir-dfe97.firebasestorage.app',
    measurementId: 'G-SL2PB3FRFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBOTnEUSl02kIu9aZD7e0qDZ6yDjxoag',
    appId: '1:885247792471:android:7d99dc000b4731d9d71a12',
    messagingSenderId: '885247792471',
    projectId: 'fir-dfe97',
    storageBucket: 'fir-dfe97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADuoqQ7huXjgWmih6XY034zO00GiPX_5E',
    appId: '1:885247792471:ios:c8d0ccc15431dc69d71a12',
    messagingSenderId: '885247792471',
    projectId: 'fir-dfe97',
    storageBucket: 'fir-dfe97.firebasestorage.app',
    iosBundleId: 'com.example.sombotPc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADuoqQ7huXjgWmih6XY034zO00GiPX_5E',
    appId: '1:885247792471:ios:c8d0ccc15431dc69d71a12',
    messagingSenderId: '885247792471',
    projectId: 'fir-dfe97',
    storageBucket: 'fir-dfe97.firebasestorage.app',
    iosBundleId: 'com.example.sombotPc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJjvV4UKEGmPaRtgauS-TNOE3W5QQmKMo',
    appId: '1:885247792471:web:dda1b302262c42d5d71a12',
    messagingSenderId: '885247792471',
    projectId: 'fir-dfe97',
    authDomain: 'fir-dfe97.firebaseapp.com',
    storageBucket: 'fir-dfe97.firebasestorage.app',
    measurementId: 'G-BKYRBQ8F81',
  );
}
